name: SocialDistance
main: com.meeku.socialdistance.Main
version: 1.0
api-version: 1.13
commands:
   penable:
      description: initiates a pandemic
      usage: /penable
   pdisable:
      description: removes the pandemic
      usage: /pdisable
   pstatus:
      description: checks the status of the pandemic
      usage: /pstatus
   psetradius:
      description: sets danger radius in range [1,127]
      usage: /psetradius <radius>
   psetduration:
      description: sets duration in range [1,1200]
      usage: /psetduration <seconds>
   psetamplifier:
      description: sets amplifier in range [0,5]
      usage: /psetamplifier <amplifier>
   ptogglemobs:
      description: toggles infection of mobs
      usage: /ptogglemobs
