name: SocialDistance
main: com.meeku.socialDistance.Main
version: 1.0
api-version: 1.13
commands:
   enable:
      description: initiates a pandemic
      usage: /enable
   disable:
      description: removes the pandemic
      usage: /disable
   status:
      description: checks the status of the pandemic
      usage: /status
   setradius:
      description: sets danger radius in range [1,10]
      usage: /setradius <radius>
   setduration:
      description: sets duration in range [1,60]
      usage: /setduration <seconds>
   setamplifier:
      description: sets amplifier in range [0,5]
      usage: /setamplifier <amplifier>
